_wandb:
    value:
        cli_version: 0.25.1
        e:
            p9maelmm487o48rbj8l51zk7wsly8r9n:
                args:
                    - data.data_root=/tmp/circuitnet_work/instance_placement/
                    - data.label_root=/home/jovyan/shared/ctrl-nxp/CircuitNet-N28/training_set/congestion/label/
                codePath: test.py
                cpu_count: 64
                cpu_count_logical: 64
                disk:
                    /:
                        total: "858574028800"
                        used: "315247386624"
                email: bitton.gilad@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: 4beba89bb9ee32b0d55af1da4d3402e4f7257062
                    remote: https://github.com/hustvl/CircuitFormer.git
                host: jupyter-gbitton0949-sdsu-edu---1c97f46d
                memory:
                    total: "540456202240"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.35
                program: /home/jovyan/CircuitFormer/test.py
                python: CPython 3.11.9
                root: /home/jovyan/CircuitFormer/exp/exp1
                startedAt: "2026-04-08T22:09:44.688617Z"
                writerId: p9maelmm487o48rbj8l51zk7wsly8r9n
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 63
                - 74
                - 103
            "2":
                - 1
                - 9
                - 41
                - 49
                - 50
                - 63
                - 74
                - 103
            "3":
                - 7
                - 16
                - 66
            "4": 3.11.9
            "5": 0.25.1
            "12": 0.25.1
            "13": linux-x86_64
data:
    value:
        batch_size: 8
        data_root: /tmp/circuitnet_work/instance_placement/
        dataset: circuitnet
        label_root: /home/jovyan/shared/ctrl-nxp/CircuitNet-N28/training_set/congestion/label/
        num_workers: 16
experiment:
    value:
        checkpoint_interval: 1000
        ckpt_path: /home/jovyan/CircuitFormer/ckpts/circuitformer.ckpt
        log_image_interval: 500
        project: circuitformer
        save_dir: /home/jovyan/CircuitFormer/exp/exp1
model:
    value:
        batch_size: 8
        label_weight: 1
        loss: mse
        loss_weight: 128
        lr: 0.0001
        lr_scheduler: cosine
        max_epochs: 100
        min_lr: 1e-06
        model_name: circuitformer
        warmup_epochs: 10
        warmup_lr: 1e-06
        weight_decay: 0
trainer:
    value:
        accelerator: auto
        check_val_every_n_epoch: 10
        devices: auto
        log_every_n_steps: 1
        max_epochs: 100
        precision: 32
        sync_batchnorm: false
